name: MY-V@s
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
        NAME : ${{ steps.creation.outputs.name }}
        TYPE : ${{ steps.creation.outputs.type }}
    steps:
      - name: Run a one-line script
        id : creation
        run: |
            echo "name=Vieer.pdf" >> $GITHUB_OUTPUT
            echo "type=pdf" >> $GITHUB_OUTPUT

      - name: githu context
        run: |
          echo ${{ github }}